version: "3"

networks:
  net:
    driver: bridge

services:
  one_image:
    build: .
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    ports:
      - "8000:8000"
      - "9051:9051"
      - "9053:9053"
      - "30002:30002"
    environment:
      Microbit_flag: "false"
      Webcam_flag: "false"
      godot_games_flag: "false"
      websocket_bridge: "true"
#      FEAGI_HOST_INTERNAL: one_image
    env_file:
      - ./.env
    privileged: true
    networks:
      - net
