version: "3"

networks:
  net:
    driver: bridge

services:
  one_image:
    build: .
    ports:
      - "9051:9051"
      - "9052:9052"
      - "9055:9055"
      - "3000"
      - "8000"
    environment:
      Microbit_flag: "true"
      Webcam_flag: "true"
      godot_games_flag: "true"
      FEAGI_HOST_INTERNAL: "192.168.50.218"
    privileged: true
    networks:
      - net

