version: "3"

networks:
  net:
    driver: bridge

services:
  one_image:
    build: .
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    ports:
      - "8000:8000"
      - "9051:9051"
      - "3000:3000"
    environment:
      Microbit_flag: "false"
      Webcam_flag: "false"
      godot_games_flag: "false"
      websocket_bridge: "false"
#      FEAGI_HOST_INTERNAL: one_image
    env_file:
      - ./.env
    privileged: true
    networks:
      - net
    volumes:
      - "/home/bwuk/feagi-agent/feagi_agent_core/feagi_agent:/usr/local/lib/python3.8/site-packages/feagi_agent"
      - "/home/bwuk/feagi/src:/opt/source-code/feagi/src"

