name: testing_microbit_ctlr_to_gcr
on:
  push:
    branches:
      - gcr-test
    paths:
      - 'embodiments/elecfreaks/cutebot/web_html_microbit/**'
      - 'generate_version.sh'
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: echo done
        run: |
          echo "done"
