name: deploy_webcam_ctrl_to_gcr_dev
on:
  push:
    branches:
      - gcr-test
    paths:
      - 'embodiments/neuraville/javascript_webcam/**'
      - 'generate_version.sh'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: echo done
        run: |
          echo "done"
