# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Testing PIP

on:
  [workflow_dispatch]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.repository == 'Neuraville/feagi-connector'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install twine
    - name: Build package then publish to pypi
      run: |
        python3 -m build feagi_connector_core/
        cd feagi_connector_core/
        python3 -m twine upload --repository testpypi dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TESTPYPI_TOKEN }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
