name: test_webcam_ctlr_to_gcr
on:
  push:
    branches:
      - gcr-test
    paths:
      - 'embodiments/neuraville/javascript_webcam/**'
      - 'generate_version.sh'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Current repo
      uses: actions/checkout@v2
    - name: Update Dockerfile
      run: |
        cd embodiments/neuraville/javascript_webcam/
        if [ -f Dockerfile.python ]; then
            sed -e 's|COPY controller.py /root/|COPY embodiments/neuraville/javascript_webcam/controller.py /root/|' \
                -e 's|COPY configuration.py /root/|COPY /embodiments/neuraville/javascript_webcam/configuration.py /root/|' \
                -e 's|COPY version.py /root/|COPY /embodiments/neuraville/javascript_webcam/version.py /root/|' \
                "Dockerfile.python" > "NewDockerfile"
        fi
        mv NewDockerfile Dockerfile.python
    - name: Push to GCR GitHub Action
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{secrets.GCR_SERVICE}}
        project_id: feagi-poc
        image_name: feagi-dev/webcam_controller
        image_tag: ${{ github.run_number }}, latest
        dockerfile: ./embodiments/neuraville/javascript_webcam/Dockerfile.python
